ALL: CrunchMain

FFLAGS  = -w

SOURCEF = \
          crunchtype.F90\
          params.F90\
          strings.F90\
          io.F90\
          concentration.F90\
          mineral.F90\
          transport.F90\
          medium.F90\
          modflowModule.F90\
          ReadFlow.F90\
          RunTime.F90\
          solver.F90\
          temperature.F90\
          flow.F90\
          crunch_interface.F90\
          CrunchFunctions.F90\
          isotope.F90\
          NanoCrystal.F90\
          CrunchTopeDriver.F90\
          CrunchTope.F90\
          AffinityNumerical.F90\
          AllocateALL.F90\
          AllocateOS3D.F90\
          AllocateGasesGimrt.F90\
          AllocateGasesOS3D.F90\
          AllocateGIMRT.F90\
          AqueousFluxInitialize.F90\
          AqueousFluxWrite.F90\
          AqueousToBulkConvert.F90\
          AssembleLocal.F90\
          AssembleGlobal.F90\
          AverageRo.F90\
          bd_diffuse.F90\
          bd_diffuse_by_grid.F90\
          bdcalc.F90\
          bdexchange.F90\
          bdgas.F90\
          bdgas_by_grid.F90\
          bdrecalc.F90\
          bdrecalc_by_grid.F90\
          bdsurf.F90\
          breakfind.F90\
          BreakFindPlusCount.F90\
          BreakthroughInitialize.F90\
          BreakthroughWrite.F90\
          CalciteBulkStoichiometry.F90\
          CalciteStoichiometry.F90\
          CalciteStoichiometryBoundary.F90\
          CalculateDHAD.F90\
          CalculateTortuosity.F90\
          coeff.F90\
          coeff_D.F90\
          coeffCylinder.F90\
          coeffCylinder_D.F90\
          coeffCylinderDiffuse.F90\
          coeffCylinderNUFT.F90\
          coeffDiffuse.F90\
          coeffNuft.F90\
          coeffSphericalNew.F90\
          coeffSphericalNew_d.F90\
          convan.F90\
          CourantStep.F90\
          CourantStepAlt.F90\
          CPUdefinition.F90\
          CrunchPETScFinalizeSolver.F90\
          CrunchPETScInitializeChemistry.F90\
          CrunchPETScInitializeDiffusion.F90\
          CrunchPETScInitializePressure.F90\
          CrunchPETScTolerances.F90\
          database.F90\
          decay.F90\
          decbt90.F90\
          density.F90\
          dispersivity.F90\
          duan.F90\
          equilib_co2.F90\
          erosion.F90\
          ex_activity.F90\
          exactivity_init.F90\
          exchange.F90\
          exchange_init.F90\
          ExchangeConcentration.F90\
          find_condition.F90\
          find_firststring.F90\
          find_string.F90\
          FindMaxFlow.F90\
          FirstAllocation.F90\
          fit.F90\
          fitgamma.F90\
          FluxWeightedConcentrationInitialize.F90\
          FluxWeightedConcentrationWrite.F90\
          FormatForNameList.F90\
          FxTopeGlobal.F90\
          FxTopeLocal.F90\
          gamma_co2.F90\
          gamma.F90\
          gamma_init_co2.F90\
          gamma_init.F90\
          gamma_local.F90\
          gascoeffCylinder.F90\
          gasdiff.F90\
          gases.F90\
          gases_init_co2.F90\
          gases_init.F90\
          GasInjection.F90\
          GetMineralNumber.F90\
          GasPartialPressure.F90\
          GasPartialPressure_Init.F90\
          GetPrimarySpeciesNumber.F90\
          GhostCells.F90\
          GIMRTCrunchPETScTolerances.F90\
          GlobalArrayAllocation.F90\
          GlobalDensity.F90\
          graphics3d.F90\
          GraphicsKaleidagraph.F90\
          GraphicsTecplot.F90\
          GraphicsVisit.F90\
          harmonic.F90\
          InitializeCalciteStoichiometry.F90\
          isotope-read_series.F90\
          IsotopeBreakthroughInitialize.F90\
          IsotopeBreakthroughWrite.F90\
          jac_exchange.F90\
          jac_exchange_local.F90\
          jac_local.F90\
          jacexchange.F90\
          jacexchange_init.F90\
          jacgas.F90\
          jacgas_local.F90\
          jacminTope.F90\
          jacobian.F90\
          jacobian_init.F90\
          jacobian_plus.F90\
          jacpotential.F90\
          JacPotentialLocal.F90\
          jacrkin.F90\
          jacsurf.F90\
          jacsurf_init.F90\
          jacsurf_local.F90\
          keqcalc2.F90\
          keqcalc2_init_co2.F90\
          keqcalc2_init.F90\
          keqcalcGasOnly.F90\
          lubksb90.F90\
          ludcmp90.F90\
          majuscules.F90\
          mindecay.F90\
          mineralfind.F90\
          mineral_update.F90\
          modread.F90\
          ModScan.F90\
          movie.F90\
          newfile.F90\
          nrerror.F90\
          NviewInit.F90\
          NviewOutput.F90\
          oldcon.F90\
          oldcongas.F90\
          oldkd.F90\
          oldsurf.F90\
          oldsurface.F90\
          os3d_newton.F90\
          PauseFor.F90\
          PestExchange.F90\
          PestSurface.F90\
          PestScaleOutput.F90\
          porcalc.F90\
          porperm.F90\
          Pressure.F90\
          PrimarySpeciesCheck.F90\
          ratecheck.F90\
          reactionTope.F90\
          reactkin.F90\
          read98.F90\
          read_AqueousFluxSeries.F90\
          read_BoundaryConditionsByZone.F90\
          read_bound.F90\
          read_burialfile.F90\
          read_CatabolicPath.F90\
          read_concentration.F90\
          read_condition.F90\
          read_constantflow.F90\
          read_constantgasflow.F90\
          read_ConstantTortuosity.F90\
          read_coordinates.F90\
          read_dbs.F90\
          read_decay.F90\
          read_diffusion.F90\
          read_dispersion.F90\
          read_equil.F90\
          read_erosion.F90\
          read_exchange.F90\
          readFileName.F90\
          read_flowfile.F90\
          read_FluxWeightedConcentration.F90\
          read_gasdiffusion.F90\
          read_gasflowfile.F90\
          read_gaspump.F90\
          read_graphics.F90\
          read_gravity.F90\
          read_het.F90\
          read_infiltration.F90\
          read_integer.F90\
          read_ionexchangeBS.F90\
          read_ionexchangeMIN.F90\
          read_Isotopes.F90\
          read_Kd.F90\
          read_kinetics_Bio.F90\
          read_logical.F90\
          read_master.F90\
          read_mineral.F90\
          read_minkin.F90\
          read_MODFLOWfile.F90\
          read_multpar.F90\
          read_multstring.F90\
          read_nuft.F90\
          read_par.F90\
          read_permfile.F90\
          read_permx.F90\
          read_permy.F90\
          read_permz.F90\
          read_pH.F90\
          read_porosity.F90\
          read_pressureAlternative.F90\
          read_pump.F90\
          read_restart.F90\
          read_series.F90\
          read_snapshot.F90\
          read_SolidDensity.F90\
          read_speciesdiffusion.F90\
          read_steady.F90\
          read_string.F90\
          read_surface.F90\
          read_surfacecomplex.F90\
          read_temp.F90\
          read_temperature.F90\
          read_title.F90\
          read_toperatio.F90\
          read_tortuosityfile.F90\
          read_TortuosityByZone.F90\
          readblock.F90\
          readbreak.F90\
          readCaseSensitive.F90\
          readCaseSensitivePar.F90\
          ReadFileNameOnly.F90\
          ReadFlowField.F90\
          readModFlowParameters.F90\
          readModFlowStress.F90\
          readRecharge.F90\
          ReadSaturation.F90\
          readSingleString.F90\
          readtype1.F90\
          readtype2.F90\
          readtype3.F90\
          readtypescan1.F90\
          reallocate.F90\
          restart.F90\
          rocalc.F90\
          satcalc.F90\
          solbt90.F90\
          SolveDiffuse.F90\
          SolveDiffuseSpherical.F90\
          SolveGasDiffuse.F90\
          speciation.F90\
          species.F90\
          species_init.F90\
          SpeciesLocal.F90\
          squeeze.F90\
          sschaine.F90\
          sschaine_hyph.F90\
          StartTope.F90\
          SteadyState.F90\
          stringlen.F90\
          stringtype.F90\
          SurfaceComplex.F90\
          surf_init.F90\
          SurfaceCharge.F90\
          SurfaceCharge_init.F90\
          SurfaceConcentration.F90\
          SurfLocal.F90\
          swap.F90\
          timestep.F90\
          tot_ex.F90\
          totconc.F90\
          totconc_init.F90\
          totconc_plus.F90\
          totexchange.F90\
          totexchange_init.F90\
          totexchange_local.F90\
          totgas.F90\
          totgas_init.F90\
          totsurf.F90\
          totsurf_init.F90\
          totsurf_local.F90\
          tridag_ser.F90\
          tvd.F90\
          tvdNuft.F90\
          units_concentration.F90\
          units_distance.F90\
          units_time.F90\
          units_timeOutput.F90\
          UpdateExchanger.F90\
          velocalc.F90\
          WaterReacted.F90\
          WaterReactedNodeByNode.F90\
          xmass.F90\
          xmassNodeByNode.F90\
          xtoolInit.F90\
          xtoolOutput.F90

OBJSF  =  crunchtype.o\
          params.o\
          strings.o\
          io.o\
          concentration.o\
          mineral.o\
          transport.o\
          medium.o\
          modflowModule.o\
          ReadFlow.o\
          RunTime.o\
          solver.o\
          temperature.o\
          flow.o\
          crunch_interface.o\
          CrunchFunctions.o\
          isotope.o\
          NanoCrystal.o\
          CrunchTopeDriver.o\
          CrunchTope.o\
          AffinityNumerical.o\
          AllocateOS3D.o\
          AllocateGIMRT.o\
          AllocateALL.o\
          AllocateGasesGimrt.o\
          AllocateGasesOS3D.o\
          AqueousFluxInitialize.o\
          AqueousFluxWrite.o\
          AqueousToBulkConvert.o\
          AssembleLocal.o\
          AssembleGlobal.o\
          AverageRo.o\
          bd_diffuse.o\
          bd_diffuse_by_grid.o\
          bdcalc.o\
          bdexchange.o\
          bdgas.o\
          bdgas_by_grid.o\
          bdrecalc.o\
          bdrecalc_by_grid.o\
          bdsurf.o\
          breakfind.o\
          BreakFindPlusCount.o\
          BreakthroughInitialize.o\
          BreakthroughWrite.o\
          CalciteBulkStoichiometry.o\
          CalciteStoichiometry.o\
          CalciteStoichiometryBoundary.o\
          CalculateDHAD.o\
          CalculateTortuosity.o\
          coeff.o\
          coeff_D.o\
          coeffCylinder.o\
          coeffCylinder_D.o\
          coeffCylinderDiffuse.o\
          coeffCylinderNUFT.o\
          coeffDiffuse.o\
          coeffNuft.o\
          coeffSphericalNew.o\
          coeffSphericalNew_d.o\
          convan.o\
          CourantStep.o\
          CourantStepAlt.o\
          CPUdefinition.o\
          CrunchPETScFinalizeSolver_OS.o\
          CrunchPETScInitializeChemistry_OS.o\
          CrunchPETScInitializeDiffusion_OS.o\
          CrunchPETScInitializePressure_OS.o\
          CrunchPETScTolerances_OS.o\
          database_OS.o\
          decay_OS.o\
          decbt90_OS.o\
          density_OS.o\
          dispersivity_OS.o\
          duan_OS.o\
          equilib_co2_OS.o\
          erosion_OS.o\
          ex_activity_OS.o\
          exactivity_init_OS.o\
          exchange_OS.o\
          exchange_init_OS.o\
          ExchangeConcentration_OS.o\
          find_condition_OS.o\
          find_firststring_OS.o\
          find_string_OS.o\
          FindMaxFlow_OS.o\
          FirstAllocation_OS.o\
          fit_OS.o\
          fitgamma_OS.o\
          FluxWeightedConcentrationInitialize_OS.o\
          FluxWeightedConcentrationWrite_OS.o\
          FormatForNameList_OS.o\
          FxTopeGlobal_OS.o\
          FxTopeLocal_OS.o\
          gamma_co2_OS.o\
          gamma_OS.o\
          gamma_init_co2_OS.o\
          gamma_init_OS.o\
          gamma_local_OS.o\
          gascoeffCylinder_OS.o\
          gasdiff_OS.o\
          gases_OS.o\
          gases_init_co2_OS.o\
          gases_init_OS.o\
          GasInjection_OS.o\
          GetMineralNumber_OS.o\
          GasPartialPressure_OS.o\
          GasPartialPressure_Init_OS.o\
          GetPrimarySpeciesNumber_OS.o\
          GhostCells_OS.o\
          GIMRTCrunchPETScTolerances_OS.o\
          GlobalArrayAllocation_OS.o\
          GlobalDensity_OS.o\
          graphics3d_OS.o\
          GraphicsKaleidagraph_OS.o\
          GraphicsTecplot_OS.o\
          GraphicsVisit_OS.o\
          harmonic_OS.o\
          InitializeCalciteStoichiometry_OS.o\
          isotope-read_series.o\
          IsotopeBreakthroughInitialize.o\
          IsotopeBreakthroughWrite.o\
          jac_exchange_OS.o\
          jac_exchange_local_OS.o\
          jac_local_OS.o\
          jacexchange_OS.o\
          jacexchange_init_OS.o\
          jacgas_OS.o\
          jacgas_local_OS.o\
          jacminTope_OS.o\
          jacobian_OS.o\
          jacobian_init_OS.o\
          jacobian_plus_OS.o\
          jacpotential_OS.o\
          JacPotentialLocal_OS.o\
          jacrkin_OS.o\
          jacsurf_OS.o\
          jacsurf_init_OS.o\
          jacsurf_local_OS.o\
          keqcalc2_OS.o\
          keqcalc2_init_co2_OS.o\
          keqcalc2_init_OS.o\
          keqcalcGasOnly_OS.o\
          lubksb90_OS.o\
          ludcmp90_OS.o\
          majuscules_OS.o\
          mindecay_OS.o\
          mineralfind_OS.o\
          mineral_update_OS.o\
          modread_OS.o\
          ModScan_OS.o\
          movie_OS.o\
          newfile_OS.o\
          nrerror_OS.o\
          NviewInit_OS.o\
          NviewOutput_OS.o\
          oldcon_OS.o\
          oldcongas_OS.o\
          oldkd_OS.o\
          oldsurf_OS.o\
          oldsurface_OS.o\
          os3d_newton_OS.o\
          PauseFor_OS.o\
          PestExchange_OS.o\
          PestSurface_OS.o\
          PestScaleOutput_OS.o\
          porcalc_OS.o\
          porperm_OS.o\
          Pressure_OS.o\
          PrimarySpeciesCheck_OS.o\
          ratecheck_OS.o\
          reactionTope_OS.o\
          reactkin_OS.o\
          read98_OS.o\
          read_AqueousFluxSeries_OS.o\
          read_BoundaryConditionsByZone_OS.o\
          read_bound_OS.o\
          read_burialfile_OS.o\
          read_CatabolicPath_OS.o\
          read_concentration_OS.o\
          read_condition_OS.o\
          read_ConstantTortuosity_OS.o\
          read_constantflow_OS.o\
          read_constantgasflow_OS.o\
          read_coordinates_OS.o\
          read_dbs_OS.o\
          read_decay_OS.o\
          read_diffusion_OS.o\
          read_dispersion_OS.o\
          read_equil_OS.o\
          read_erosion_OS.o\
          read_exchange_OS.o\
          readFileName_OS.o\
          read_flowfile_OS.o\
          read_FluxWeightedConcentration_OS.o\
          read_gasdiffusion_OS.o\
          read_gasflowfile_OS.o\
          read_gaspump_OS.o\
          read_graphics_OS.o\
          read_gravity_OS.o\
          read_het_OS.o\
          read_infiltration_OS.o\
          read_integer_OS.o\
          read_ionexchangeBS_OS.o\
          read_ionexchangeMIN_OS.o\
          read_Isotopes_OS.o\
          read_Kd_OS.o\
          read_kinetics_Bio_OS.o\
          read_logical_OS.o\
          read_master_OS.o\
          read_mineral_OS.o\
          read_minkin_OS.o\
          read_MODFLOWfile_OS.o\
          read_multpar_OS.o\
          read_multstring_OS.o\
          read_nuft_OS.o\
          read_par_OS.o\
          read_permfile_OS.o\
          read_permx_OS.o\
          read_permy_OS.o\
          read_permz_OS.o\
          read_pH_OS.o\
          read_porosity_OS.o\
          read_pressureAlternative_OS.o\
          read_pump_OS.o\
          read_restart_OS.o\
          read_series_OS.o\
          read_snapshot_OS.o\
          read_SolidDensity_OS.o\
          read_speciesdiffusion_OS.o\
          read_steady_OS.o\
          read_string_OS.o\
          read_surface_OS.o\
          read_surfacecomplex_OS.o\
          read_temp_OS.o\
          read_temperature_OS.o\
          read_title_OS.o\
          read_toperatio_OS.o\
          read_tortuosityfile_OS.o\
          read_TortuosityByZone_OS.o\
          readblock_OS.o\
          readbreak_OS.o\
          readCaseSensitive_OS.o\
          readCaseSensitivePar_OS.o\
          ReadFileNameOnly_OS.o\
          ReadFlowField_OS.o\
          readModFlowParameters_OS.o\
          readModFlowStress_OS.o\
          readRecharge_OS.o\
          ReadSaturation_OS.o\
          readSingleString_OS.o\
          readtype1_OS.o\
          readtype2_OS.o\
          readtype3_OS.o\
          readtypescan1_OS.o\
          reallocate_OS.o\
          restart_OS.o\
          rocalc_OS.o\
          satcalc_OS.o\
          solbt90_OS.o\
          SolveDiffuse_OS.o\
          SolveDiffuseSpherical_OS.o\
          SolveGasDiffuse_OS.o\
          speciation_OS.o\
          species_OS.o\
          species_init_OS.o\
          SpeciesLocal_OS.o\
          squeeze_OS.o\
          sschaine_OS.o\
          sschaine_hyph_OS.o\
          StartTope_OS.o\
          SteadyState_OS.o\
          stringlen_OS.o\
          stringtype_OS.o\
          SurfaceComplex_OS.o\
          surf_init_OS.o\
          SurfaceCharge_OS.o\
          SurfaceCharge_init_OS.o\
          SurfaceConcentration_OS.o\
          SurfLocal_OS.o\
          swap_OS.o\
          timestep_OS.o\
          tot_ex_OS.o\
          totconc_OS.o\
          totconc_init_OS.o\
          totconc_plus_OS.o\
          totexchange_OS.o\
          totexchange_init_OS.o\
          totexchange_local_OS.o\
          totgas_OS.o\
          totgas_init_OS.o\
          totsurf_OS.o\
          totsurf_init_OS.o\
          totsurf_local_OS.o\
          tridag_ser_OS.o\
          tvd_OS.o\
          tvdNuft_OS.o\
          units_concentration_OS.o\
          units_distance_OS.o\
          units_time_OS.o\
          units_timeOutput_OS.o\
          UpdateExchanger_OS.o\
          velocalc_OS.o\
          WaterReacted_OS.o\
          WaterReactedNodeByNode_OS.o\
          xmass_OS.o\
          xmassNodeByNode_OS.o\
          xtoolInit_OS.o\
          xtoolOutput_OS.o

LOCDIR   = ${CrunchTope_Dir}

## For PETSc 3.0X
##include ${PETSC_DIR}/conf/base
## For PETSc 3.2X
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

CrunchMain : ${OBJSF} chkopts
	-${FLINKER} -o CrunchTope ${OBJSF} ${PETSC_FORTRAN_LIB} ${PETSC_LIB} ${FFLAGS}

clean ::
	$(RM) CrunchTope *.o *.mod *~
